version: '3.9'

#name: '${DOCKER_DOMAIN}'

networks:
  dev:
    driver: bridge

volumes:
  mysql_db_data:
    driver: local
  maria_db_data:
    driver: local
  pgsql_db_data:
    driver: local
  redis_db_data:
    driver: local
  redisinsight_data:
    driver: local

services:
  httpd:
    container_name: ${DOCKER_DOMAIN}-httpd
    image: php:8.0-apache
    build:
      context: .
      dockerfile: Dockerfile_Httpd
    volumes:
      - ./:/var/www/html/
    ports:
      - ${DOCKER_HTTPD_PORT}:80
    networks:
      - dev
    depends_on:
      - db_mysql
      - mailcatcher

  db_mysql:
    container_name: ${DOCKER_DOMAIN}-mysql
    image: mysql:8.0.33
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - dev
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: ${DOCKER_DOMAIN}-phpmyadmin
    image: phpmyadmin:5.2
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    networks:
      - dev
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DOCKER_DOMAIN}-${DB_CONNECTION}
      - PAM_PORT=${DOCKER_MYSQL_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db_mysql

  mailcatcher:
    container_name: ${DOCKER_DOMAIN}-mailcatcher
    image: schickling/mailcatcher
    ports:
      - ${DOCKER_MAILCATCHER_WEB}:1080
      - ${DOCKER_MAILCATCHER_SMTP}:1025
    restart: unless-stopped
    networks:
      - dev

  redis:
    container_name: ${DOCKER_DOMAIN}-redis
    image: redis:7.0.11-alpine
    ports:
      - ${DOCKER_REDIS_PORT}:6379
    volumes:
      - redis_db_data:/data
    networks:
      - dev
    restart: always
    depends_on:
      - httpd

  redisinsight:
    container_name: ${DOCKER_DOMAIN}-redisinsight
    image: redislabs/redisinsight:1.14.0
    ports:
      - ${DOCKER_REDISINSIGHT_PORT}:8001
    volumes:
      - redisinsight_data:/db
    networks:
      - dev
    environment:
      - REDIS_URI=redis://${DOCKER_DOMAIN}-redis:6379
    restart: unless-stopped
